version: '2'
services:
  web-nginx:
    image: nginx
    volumes:
    - ./nginx/sites-enabled/test.conf:/etc/nginx/conf.d/default.conf
    - /tmp:/var/log/nginx
    - /Users/thomas/work/sites/Extrabux-Complete:/usr/share/nginx/www
    ports:
    - "80:80"
    - "443:443"
    links:
    - php-fpm
  php-fpm:
    image: php7-dev
    volumes:
    - /Users/thomas/work/sites/Extrabux-Complete:/usr/share/nginx/www
    links:
    - redis
    - memcached
    - mysql
  mysql:
    image: mysql
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3308:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
  redis:
    image: redis:3.0
    container_name: redis1
    volumes:
    - ./redis:/data
    ports:
    - "6379:6379"
  memcached:
    image: memcached
    ports:
    - "3306:3306"
  elasticsearch:
    image: elasticsearch-ik-2.3
    ports:
    - "9200:9200"

